spring:
  application:
    name: Decathlon
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.change_log_master.xml

  datasource:
    url: jdbc:h2:mem:decathlon_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console